# Generated by Django 4.0.4 on 2022-06-22 16:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Predmeti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ime', models.CharField(max_length=255)),
                ('Kod', models.CharField(max_length=16)),
                ('Program', models.TextField()),
                ('Bodovi', models.IntegerField()),
                ('Sem_redovni', models.IntegerField()),
                ('Sem_Izvanredni', models.IntegerField()),
                ('Izborni', models.CharField(choices=[('Ne', 'Ne'), ('Da', 'Da')], default='Da', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Uloge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titula', models.CharField(choices=[('Administrator', 'Adminmistrator'), ('Profesor', 'Profesor'), ('Student', 'Student')], default='Student', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Korisnici',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('Email', models.EmailField(default='test@test.com', max_length=255, unique=True)),
                ('Status', models.CharField(choices=[('None', 'None'), ('Redovni', 'Redovni'), ('Izvanredni', 'Izvanredni')], default='Redovni', max_length=10)),
                ('Roles', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SustavZaUpisStudenata.uloge')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Upisi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Status', models.CharField(max_length=64)),
                ('PredmetID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SustavZaUpisStudenata.predmeti')),
                ('StudentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('StudentID', 'PredmetID')},
            },
        ),
        migrations.AddField(
            model_name='predmeti',
            name='Upisni',
            field=models.ManyToManyField(through='SustavZaUpisStudenata.Upisi', to=settings.AUTH_USER_MODEL),
        ),
    ]
