# Generated by Django 4.0.4 on 2022-06-22 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SustavZaUpisStudenata', '0002_predmeti_nositeljkolegija'),
    ]

    operations = [
        migrations.AddField(
            model_name='predmeti',
            name='Status',
            field=models.CharField(choices=[('Upisan', 'Upisan'), ('Polozen', 'Polozen'), ('Izgubio potpis', 'Izgubio potpis')], default='Upisan', max_length=15),
        ),
    ]
