# Generated by Django 4.0.4 on 2022-06-23 01:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SustavZaUpisStudenata', '0005_alter_upisi_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predmeti',
            name='NositeljKolegija',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Nositelj', to=settings.AUTH_USER_MODEL),
        ),
    ]
